version: '3'

services:
  db:
    container_name: pytest_peche_postgres
    image: postgres:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - ylab_project_pytest


  redis:
    container_name: peche_redis_pytest
    image: redis:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ylab_project_pytest


  pytest:
    container_name: pytest_peche
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      fastapi:
        condition: service_started
    networks:
      - ylab_project_pytest
    command: sh -c "pytest -v"


  fastapi:
    container_name: peche_fastapi_pytest
    build:
      context: .
    command: uvicorn application.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - ylab_project_pytest
    restart: always
    depends_on:
      - db
      - redis

networks:
  ylab_project_pytest:
    driver: bridge
